repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.4.0
    hooks:
    -   id: editorconfig-checker

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black

-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-bandit==3.0.0
        -   flake8-bugbear==22.7.1
        -   flake8-builtins==1.5.3
        -   flake8-comprehensions==3.10.0
        -   flake8-docstrings==1.6.0
        -   flake8-pytest-style==1.6.0
        -   pep8-naming==0.13.0

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy

-   repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
    -   id: cmake-format
        additional_dependencies: [pyyaml==6.0]
    -   id: cmake-lint
        additional_dependencies: [pyyaml==6.0]

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
    -   id: gitlint
