image:
  - Visual Studio 2013
  - Visual Studio 2015

configuration: Release

build:
  project: test.sln
  verbosity: detailed

before_build:
  - cmake .

after_build:
  - dir
  - dir Release
  - Release\test.exe

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
