name: Run tutorial notebook in Docker
description: Execute the specified notebook within a Docker container.
inputs:
  working-directory:
    description: Working directory.
    default: .
  notebook:
    description: Notebook to be executed.
    required: true
  artifacts:
    description: Artifacts to be uploaded.
    default: ''

runs:
  using: composite
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Download the image uploaded as an artifact in the "build" job
      uses: actions/download-artifact@v4
      with:
        name: image
        path: /tmp

    - name: Load the image
      run: |
        docker load --input /tmp/myimage.tar
        docker image ls -a

    - name: Prepare a shared volume
      run: |
        mkdir shared
        git -C shared clone --depth=1 --branch test-docker-notebooks https://github.com/tueda/test1.git

    - name: Download artifacts uploaded by previous test jobs
      uses: actions/download-artifact@v4
      with:
        name: artifact
        path: shared/test1

    - name: Run the notebook in a container
      run: >
        docker run
          --rm myimage:latest
          -v shared:/home/shared
          -w /home/shared/test1/${{ working-directory }}
          bash -c "python3 -m pip install --no-cache-dir papermill && papermill ${{ inputs.notebook }} ${{ inputs.notebook }}"

    - name: Construct artifact paths
      id: artifact-paths
      run: >
        for f in ${{ inputs.artifacts }}; do
          echo "${{ working-directory }}/$f" >>$GITHUB_OUTPUT
        done

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifact
        path: ${{ inputs.artifacts }}
        if-no-files-found: error
