name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-latex-base

      - run: apt-get download texlive-latex-base
      - run: dpkg --unpack texlive-latex-base_*.deb
      - run: dpkg --configure texlive-latex-base

      # - run: sudo apt-get install texlive-latex-base
      # - run: sudo dpkg-reconfigure texlive-latex-base

      - run: pdflatex test.tex

      - uses: actions/upload-artifact@v3
        with:
          name: doc
          path: test.pdf
          if-no-files-found: error
