name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: texlive-latex-base

      - run: sudo find / -name '*.deb'

      - run: ls -1 /var/lib/dpkg/info/*.*
  
      # - run: apt-get download texlive-base
      # - run: sudo dpkg --unpack texlive-base_*.deb
      # - run: sudo dpkg --ignore-depends=texlive-binaries --configure texlive-base

      - run: pdflatex test.tex

      - uses: actions/upload-artifact@v3
        with:
          name: doc
          path: test.pdf
          if-no-files-found: error
