name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: Upload the image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: /tmp/myimage.tar

  test-1:
    needs: build
    uses: ./.github/workflows/run-tutorial-notebook-in-docker.yml
    with:
      working-directory: examples/tutorial
      notebook: test-1.ipynb
      artifacts: test-1.out

  test-2:
    needs: test-1
    uses: ./.github/workflows/run-tutorial-notebook-in-docker.yml
    with:
      working-directory: examples/tutorial
      notebook: test-2.ipynb
      artifacts: test-2.out

  test-3:
    needs: test-2
    uses: ./.github/workflows/run-tutorial-notebook-in-docker.yml
    with:
      working-directory: examples/tutorial
      notebook: test-3.ipynb
