name: Test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest]
        cc: [gcc-9, gcc-10]
    runs-on: ${{ matrix.os }}
    steps:
      - run: ${{ matrix.cc }} -Q --help=common | grep fcommon