name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget -O https://raw.githubusercontent.com/opencv/opencv/3.4/samples/data/fruits.jpg

      - uses: actions/upload-artifact@v4
        id: upload
        with:
          path: fruits.jpg

      - run: |
          echo "![Image](${{ steps.upload.outputs.artifact-url }})" >>$GITHUB_STEP_SUMMARY
          echo "![Image](${{ steps.upload.outputs.artifact-url }}/fruits.jpg)" >>$GITHUB_STEP_SUMMARY
