name: Test

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: tueda/setup-form@v1
        with:
          form-version: '4.3.1'
      - run: form -v
